/**
 * TypeScript types mirroring the backend enquiry schemas.
 * Source of truth: services/api/app/modules/enquiries/schemas.py
 */

export type Enquiry = {
  id: string;
  restaurant_id: string;
  persona_id: string | null;
  reference: string;
  status: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  company_name: string | null;
  party_size: number | null;
  event_date: string | null;
  event_type: string | null;
  budget_indication: string | null;
  preferred_area: string | null;
  dietary_requirements: string | null;
  special_requests: string | null;
  message: string | null;
  source: string;
  recommended_minimum_spend: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type EnquiryListOut = {
  items: Enquiry[];
  total: number;
};

/**
 * Response from POST /enquiries/intake.
 * Mirrors backend EnquiryIntakeOut schema.
 */
export type EnquiryIntakeOut = {
  enquiry_id: string;
  reference: string;
  status: string;
  restaurant_id: string;
  persona_id: string | null;
  persona_name: string | null;
  audience_type: string | null;
  recommended_minimum_spend: number;
  pricing_explanation: string;
  created_at: string;
};

export type EnquiryMessage = {
  id: string;
  enquiry_id: string;
  direction: string; // inbound | outbound
  channel: string;
  subject: string | null;
  body: string;
  sent_at: string | null;
  created_at: string;
};

/**
 * AI transparency context returned with every generated draft.
 * Mirrors AIContextOut in services/api/app/modules/ai/schemas.py.
 */
export type AIContextOut = {
  model: string;
  is_fallback: boolean;
  persona_name: string | null;
  persona_tone: string | null;
  persona_style: string | null;
  guest_message_used: string | null;
  room_name: string | null;
  recommended_minimum_spend: number | null;
  system_prompt: string | null;   // null when fallback provider was used
  user_message: string | null;    // null when fallback provider was used
};

/**
 * Single availability slot for a room meal period.
 */
export type RoomAvailabilitySlot = {
  meal_period: string;   // "lunch" | "dinner"
  status: string;        // "available" | "booked" | "held" | "unavailable"
  notes: string | null;
};

/**
 * Room availability response from GET /restaurants/{id}/rooms/{rid}/availability.
 */
export type RoomAvailabilityOut = {
  room_id: string;
  room_name: string;
  date: string;
  slots: RoomAvailabilitySlot[];
};

/**
 * Summary of the extraction step returned with FreeformIntakeOut.
 * Mirrors ExtractionSummaryOut in services/api/app/modules/enquiries/schemas.py.
 */
export type ExtractionSummaryOut = {
  extraction_id: string | null;
  prompt_run_id: string | null;
  is_fallback: boolean;
  validation_status: string | null;
  guest_count: number | null;
  event_date: string | null;
  event_type: string | null;
  missing_fields: string[] | null;
  // AI transparency: prompts and raw response from the extraction LLM call
  extraction_system_prompt: string | null;
  extraction_user_prompt: string | null;
  extraction_raw_response: string | null;
};

/**
 * Response from POST /enquiries/intake/freeform.
 * Includes extraction summary, recommended action, and generated draft.
 * Mirrors FreeformIntakeOut in services/api/app/modules/enquiries/schemas.py.
 */
export type FreeformIntakeOut = {
  enquiry_id: string;
  reference: string;
  status: string;
  restaurant_id: string;
  persona_id: string | null;
  persona_name: string | null;
  audience_type: string | null;
  created_at: string;
  extraction: ExtractionSummaryOut | null;
  recommended_action: string | null;
  draft_subject: string | null;
  draft_body: string | null;
  draft_message_id: string | null;
  draft_is_fallback: boolean | null;
  draft_ai_context: AIContextOut | null;
};

/**
 * Draft response generated by the AI service for an enquiry.
 * Mirrors the backend DraftResponseOut schema.
 */
export type EnquiryDraft = {
  enquiry_id: string;
  message_id: string;
  subject: string | null;
  body: string;
  generated_at: string;
  is_fallback: boolean | null;
  model: string | null;
  persona_name: string | null;
  ai_context: AIContextOut | null;
};

/**
 * Latest extraction record for an enquiry.
 * Mirrors EnquiryExtractionOut in services/api/app/modules/enquiries/schemas.py.
 * Returned by GET /enquiries/{id}/extractions/latest.
 */
export type EnquiryExtractionOut = {
  id: string;
  enquiry_id: string;
  tenant_id: string | null;
  extracted_json: Record<string, unknown> | null;
  normalized_json: Record<string, unknown> | null;
  missing_fields: string[] | null;
  confidence_json: Record<string, unknown> | null;
  created_at: string;
};

/**
 * Latest processing snapshot for an enquiry.
 * Mirrors EnquiryProcessingSnapshotOut in services/api/app/modules/enquiries/schemas.py.
 * Returned by GET /enquiries/{id}/processing/latest.
 */
export type EnquiryProcessingSnapshotOut = {
  id: string;
  enquiry_id: string;
  extraction_id: string | null;
  recommended_action: string | null;
  availability_result_json: Record<string, unknown> | null;
  room_suitability_json: Record<string, unknown> | null;
  pricing_result_json: Record<string, unknown> | null;
  missing_fields_json: string[] | null;
  created_at: string;
};

/**
 * Email delivery event record from email_events table.
 * Mirrors the backend EmailEvent model.
 */
export type EmailEventRecord = {
  id: string;
  enquiry_id: string | null;
  direction: string; // inbound | outbound
  status: string; // sent | failed | disabled | received | queued | sending
  from_address: string;
  to_address: string;
  subject: string;
  error: string | null;
  created_at: string;
};
