import uuid
from datetime import date, datetime
from typing import TYPE_CHECKING

from sqlalchemy import Date, DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.modules.restaurants.models import Restaurant


class DemandEvent(Base):
    """A demand signal for a restaurant on a specific date and meal period.

    Records are seeded with fake data for the POC and represent anticipated
    or observed demand levels (e.g. high demand on a bank holiday weekend).
    No live third-party demand integration is used in the POC.
    """

    __tablename__ = "demand_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    restaurant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("restaurants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    event_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    # breakfast / lunch / dinner / all
    meal_period: Mapped[str] = mapped_column(String(20), nullable=False, default="all")
    # low / medium / high / very_high
    demand_level: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    # Optional 0–1 score for graduated demand display
    demand_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    # seeded / manual
    source: Mapped[str] = mapped_column(String(20), nullable=False, default="seeded")
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    restaurant: Mapped["Restaurant"] = relationship(
        "Restaurant", back_populates="demand_events"
    )


class InsightSnapshot(Base):
    """A pre-computed analytics snapshot for a restaurant over a time period.

    Snapshots are generated by a background Celery task and stored here so the
    dashboard can read them without running live aggregation queries.
    """

    __tablename__ = "insight_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # None means the snapshot covers all restaurants (aggregate view).
    restaurant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("restaurants.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    # weekly / monthly / annual
    snapshot_type: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    # Snapshot payload — metrics dict written by the Celery insights task
    data: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Relationships
    restaurant: Mapped["Restaurant | None"] = relationship(
        "Restaurant", back_populates="insight_snapshots"
    )
